#ifndef APPCONSTANT_H_INCLUDED
#define APPCONSTANT_H_INCLUDED
#define COMPANY_NAME_LEN    64
#define SHARE_NAME_LEN      64
#define SHARE_DATE_LEN      32
#define SHARE_PRICE_LEN      64
#define SHARE_QUANTITY_LEN      64




#endif // APPCONSTANT_H_INCLUDED
